### ISSUE TITLE
clean up setup_environment.sh

### ISSUE THREAD

**Issue by cjayb** [cfin-tools/configurations#3]
Make setup_environment.sh aware of the host it's being called on.
Separate all host-specific stuff (like /opt* on isis) from general utilities
Consider long-term strategy for bin software installations (should we
move freesurfer & mne-C to hyades:/usr/local/common ?)

**Comment by MadsJensen** [comment]
+1
It would be useful make setup_environment.sh aware of the host. And I think it might be better to move to a "hyades-style" folder layout as it would make it easier for people only to learn one structure.
